FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY bot.py .
COPY config.json .
COPY subs.json .
COPY logs.txt .

CMD ["python", "bot.py"]
