FROM python:3.11-slim

WORKDIR /app

# Copy API dependencies
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy API source
COPY app.py .

CMD ["gunicorn", "-b", "0.0.0.0:5000", "app:app"]
