FROM node:20

WORKDIR /app

COPY package.json .
COPY vite.config.js .
RUN npm install

COPY . .

RUN npm run build

# serve build with nginx
FROM nginx:alpine
COPY --from=0 /app/dist /usr/share/nginx/html
EXPOSE 3000
CMD ["nginx", "-g", "daemon off;"]
